### ISSUE TITLE
Lo pongo a funcionar?

### ISSUE THREAD

**Issue by jamlfy** [colombia-dev/hubot#1]
Pues pregunto, si lo pongo a funcionar... La verdad, ni se si esta en funcionamiento, pero no me cuesta nada ponerlo sobre ruedas.

**Comment by ivancamilov** [comment]
Hola @alejonext, conchita ya está vivita y coleando desde hace unas semanas en el Slack de colombia-dev.

**Comment by jamlfy** [comment]
Y el @ ??

**Comment by ivancamilov** [comment]
No te entiendo muy bien la pregunta, ¿a que te refieres con 'el @'?

**Comment by buritica** [comment]
@alejonext en el slack encuentras a `conchita`. Si quieres saber como funciona le puedes mandar un DM con el comando help. o `/msg conchita help`. Si la quieres usar en un canal, debes asegurarte que esta en el canal, la puedes invitar con @conchita.
